### ISSUE TITLE
usage of svg not possible with sphinx LaTeX output

### ISSUE THREAD

**Issue by fietew** [TWOEARS/documentation#31]
As we want to use the LaTeX output for the database deliverable, we somehow have to replace the zenodo svg files with pdf, png or something like that.

@hagenw: any preferences?

**Comment by hagenw** [comment]
Ah, good point.
Then I would prefer to use plain text instead.

``` rst
`10.5281/zenodo.164413 <https://doi.org/10.5281/zenodo.164413>`
```

My second choice would be a png image, if you prefer that one.

**Comment by fietew** [comment]
Okay, I will create a pull request for that.
