### ISSUE TITLE
List of impulse responses

### ISSUE THREAD

**Issue by hagenw** [TWOEARS/documentation#37]
On the start page for the impulse responses there is a list of all available HRTFs and BRIRs:
http://docs.twoears.eu/en/latest/database/impulse-responses/

This list is not up-to-date.

The easiest solution might be to just remove the list on that page?

**Comment by fietew** [comment]
I think, this list would be(at least now) way too long. I agree, that this list can be deleted.

**Comment by hagenw** [comment]
OK, I leave it to you to do it ;)
