### ISSUE TITLE
Missing parts in the rosAFE section.

### ISSUE THREAD

**Issue by hagenw** [TWOEARS/documentation#49]
We have a nice section on all the related rosAFE stuff: http://docs.twoears.eu/en/latest/robo/rosafe

At the end of its third section there are a few subsection missing, starting with http://docs.twoears.eu/en/latest/robo/rosafe/rosafe/#other-services
The fourth section http://docs.twoears.eu/en/latest/robo/rosafe/matlab_client/ is also missing.

@antonyomusabini, @sylarevan: Are you able to add the missing parts? If yes, can you please create a pull request where you add your changes.

**Comment by sylvarg** [comment]
Yep, I'm on it. I will try to do that ASAP.

**Comment by hagenw** [comment]
OK, thank you.

**Comment by sylvarg** [comment]
I have just pushed modifications concerning rosAFE in a new "rosAFE" branch, which is identical to the master one, for now (I can't then create a pull request). Do I let you merge everything?

**Comment by hagenw** [comment]
It would be cool if you can push all your updates into this new `rosAFE` branch. When you are finished please create the pull request and I will then shortly review and merge your changes (or ask for small corrections first).

**Comment by sylvarg** [comment]
Done.  (Up to minor spelling mistakes I just spot...)
#54
