### ISSUE TITLE
Getting started robot section is empty

### ISSUE THREAD

**Issue by hagenw** [TWOEARS/documentation#63]
See: http://docs.twoears.eu/en/latest/robo/getting-started/

There is of course already an introduction to the robotic part available under the first steps section:
http://docs.twoears.eu/en/latest/intro/tutorial-robot/

But I would suggest we need also some text here for an intro to this section.
@thomforgue, @PatrickDanes, @sylarevan, @antonyomusabini: or what do you think?

**Comment by thomforgue** [comment]
See comments on #59 :wink:
